# Generated by Django 6.0.2 on 2026-02-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('pc_id', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('code_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('available', 'ว่าง'), ('in_use', 'ใช้งานอยู่'), ('reserved', 'จองแล้ว'), ('maintenance', 'แจ้งซ่อม')], default='available', max_length=20)),
                ('pc_type', models.CharField(default='General', max_length=20)),
                ('installed_software', models.JSONField(default=list, help_text='List of installed software')),
                ('current_user', models.CharField(blank=True, max_length=100, null=True)),
                ('session_start', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(default='CKLab', max_length=100)),
                ('max_session_minutes', models.PositiveIntegerField(default=120)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('announcement', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('software_type', models.CharField(choices=[('AI', 'AI Tool'), ('Software', 'General Software')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(default='Guest', max_length=50)),
                ('user_faculty', models.CharField(default='-', max_length=100)),
                ('user_level', models.CharField(default='-', max_length=50)),
                ('user_year', models.CharField(default='-', max_length=50)),
                ('pc_id', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('used_software', models.JSONField(default=list)),
                ('is_ai_used', models.BooleanField(default=False)),
                ('slot_id', models.CharField(default='Unlimited', max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
            ],
        ),
    ]
