# Generated by Django 6.0.2 on 2026-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='computer',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='installed_software',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='pc_id',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='pc_type',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='session_start',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='software',
            name='name',
        ),
        migrations.RemoveField(
            model_name='software',
            name='software_type',
        ),
        migrations.RemoveField(
            model_name='software',
            name='version',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='satisfaction_score',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='user_name',
        ),
    ]
